sudo: required
services:
  - docker

before_install:
  - docker build -t jhomiguel/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true jhomiguel/react-test npm run test -- --coverage

after_success:
  - docker build -t jhomiguel/complex-client ./client
  - docker build -t jhomiguel/complex-nginx ./nginx
  - docker build -t jhomiguel/complex-server ./server
  - docker build -t jhomiguel/complex-worker ./worker
  #Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images to docker hub
  - docker push jhomiguel/complex-client
  - docker push jhomiguel/complex-nginx
  - docker push jhomiguel/complex-server
  - docker push jhomiguel/complex-worker
